"""empty message

Revision ID: 9c3531d03cb4
Revises: afe328990b1f
Create Date: 2020-10-22 16:17:14.749577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3531d03cb4'
down_revision = 'afe328990b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=80), nullable=False),
    sa.Column('encore', sa.Integer(), nullable=False),
    sa.Column('affiliates', sa.LargeBinary(length=128), nullable=True),
    sa.Column('virtual_product', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encore'),
    sa.UniqueConstraint('product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costs')
    # ### end Alembic commands ###
