"""empty message

Revision ID: ad11788da75a
Revises: 9c3531d03cb4
Create Date: 2020-10-22 17:17:53.666668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad11788da75a'
down_revision = '9c3531d03cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_name', sa.String(length=80), nullable=False),
    sa.Column('aov', sa.Integer(), nullable=False),
    sa.Column('epc', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funnel_name')
    )
    op.add_column('costs', sa.Column('affiliate', sa.Integer(), nullable=True))
    op.add_column('costs', sa.Column('product_cost', sa.Integer(), nullable=False))
    op.add_column('costs', sa.Column('product_name', sa.String(length=80), nullable=False))
    op.add_column('costs', sa.Column('shipping', sa.Integer(), nullable=True))
    op.drop_column('costs', 'affiliates')
    op.drop_column('costs', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costs', sa.Column('product', sa.VARCHAR(length=80), nullable=False))
    op.add_column('costs', sa.Column('affiliates', sa.BLOB(), nullable=True))
    op.drop_column('costs', 'shipping')
    op.drop_column('costs', 'product_name')
    op.drop_column('costs', 'product_cost')
    op.drop_column('costs', 'affiliate')
    op.drop_table('funnels')
    # ### end Alembic commands ###
