"""empty message

Revision ID: c3ef86e6a402
Revises: ea855f8fa72e
Create Date: 2020-10-29 13:21:41.328881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ef86e6a402'
down_revision = 'ea855f8fa72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costs', sa.Column('funnel_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'costs', ['product_name'])
    op.create_foreign_key(None, 'costs', 'funnels', ['funnel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('costs', 'virtual_product')
    op.drop_column('costs', 'encore')
    op.add_column('funnels', sa.Column('aff_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funnels', 'aff_cost')
    op.add_column('costs', sa.Column('encore', sa.INTEGER(), nullable=False))
    op.add_column('costs', sa.Column('virtual_product', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'costs', type_='foreignkey')
    op.drop_constraint(None, 'costs', type_='unique')
    op.drop_column('costs', 'funnel_id')
    # ### end Alembic commands ###
